### ISSUE TITLE
use Standalone Client Tips: Error: ws does not work in the browser. Browser clients must use the native WebSocket object

### ISSUE THREAD

**Issue by zddyx258** [WalletConnect/walletconnect-monorepo#1062]
Error: ws does not work in the browser. Browser clients must use the native WebSocket object

**Comment by ujjwalbishnoi** [comment]
Same error occured in production using vite react-ts

**Comment by marherb** [comment]
> Same error occured in production using vite react-ts

error is `global is not define`
may edit vite.config.js
`export default defineConfig({
   ...,
    define: {
        global: "globalThis",
    },
});`
and then add Buffer in main.ts
`
import { Buffer } from "buffer";
window.Buffer = Buffer;
`

**Comment by Arslan-95** [comment]
```
error Error: ws does not work in the browser. Browser clients must use the native WebSocket object
    at new module.exports (...\node_modules\@walletconnect\socket-transport\node_modules\ws\browser.js:4:1)
```
I cant fix it. Who know, how to do it?

**Comment by finessevanes** [comment]
Is this still an issue?

**Comment by MacroChip** [comment]
@finessevanes yes for vite projects (maybe not vite 4 tho). @marherb 's solution does work, but is a little heavy handed (i.e. the string "global" is replaced with "globalThis" so things like "global-warming" become "globalThis-warming".

**Comment by MacroChip** [comment]
A slightly more surgical approach is to use `"global.WebSocket": "globalThis.WebSocket",` instead of `global: "globalThis"`
@marherb if you want, edit your post if it works for you

**Comment by finessevanes** [comment]
@MacroChip what API are you using?

**Comment by MacroChip** [comment]
@finessevanes Did some diving because I am not using it directly. TLDR I think walletconnect v2 fixed this. 
I am also integrating Pera (linked above at https://github.com/perawallet/connect/issues/101)
Only moderate confidence on the following:
Pera connect ultimately gets to [@walletconnect/http](https://github.com/WalletConnect/walletconnect-monorepo/blob/7f5985bc9dd023e432b534160bdeba8925ad9225/packages/helpers/socket-transport/src/index.ts#L19) which seems to have disappeared in walletconnect v2. The spiritual successor is
https://github.com/WalletConnect/walletconnect-utils/blob/24f59297429ee351d741d3fb84e558f0a1ede159/jsonrpc/ws-connection/src/ws.ts#L21
which, I believe, would not cause an error.

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
