### ISSUE TITLE
"typeof global.WebSocket" check in @walletconnect/jsonrpc-ws-connection is causing issues

### ISSUE THREAD

**Issue by yekta** [WalletConnect/walletconnect-monorepo#1299]
**Describe the bug**
The check in `@walletconnect/socket-transport/dist/esm/index.js` is causing issues in some environments (I'm using SvelteKit + Vite):

```const WS = typeof global.WebSocket !== "undefined" ? global.WebSocket : require("ws");```

The specific error it causes is `global is not defined`. Given it imports "ws" if `global.WebSocket` is not there, seems like it could also check if `global` exists before checking if `global.WebSocket` exists. I'm not familiar with all the requirements and reasons for this check but if I change the check, everything works.

**Expected behavior**
No `global is not defined` error even when `global` doesn't exist.

**Comment by pyncz** [comment]
Webpack sets the `global` field, but Vite doesn't. Workaround is to set this field by yourself somewhere near init code of the client side.
```js
window.global ||= window
```
I don't know where it can be in the context of svelte, but for Nuxt (Vue) it can be in some client plugin, `~/plugins/init.client.ts`, for example.

P.S. Still a bug since the relying on such bundler-specific fields doesn't seem to be a good idea.

**Comment by bkrem** [comment]
Fixed in https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.1.4

Please let us know if this is still reproducible and we'll reopen.
