### ISSUE TITLE
No matching Key. expirer

### ISSUE THREAD

**Issue by abdulhaseeb4239** [WalletConnect/walletconnect-monorepo#1514]
**Describe the bug**
I am working on wallet connect integration in react-native. 
After a few minutes of connection, I get this exception. 
Is there something I am missing when handling the expiry of the connection? 

```
{"context": "client"} {"context": "client/expirer"} No matching key. expirer: topic:id:1665008019573973
 ERROR  {"context": "client"} {"context": "client/expirer"} No matching key. expirer: topic:9049928fb13a3e4bac762ea40622f9f3de346a69ef8d3070378181a0e3517f12
```

**SDK Version (if relevant)**
"@walletconnect/react-native-compat": "^2.0.0-rc.3",
"@walletconnect/sign-client": "2.0.0-rc.3",
"@walletconnect/utils": "2.0.0-rc.3",

**Comment by bkrem** [comment]
Hi @abdulhaseeb4239,

Thanks for reporting this.

This was a minor issue in the internal expirer logic, and was fixed as part of  the `2.0.0-rc.4` release we just published:
https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.0.0-rc.4

Updating to `rc.4` should resolve this. Please comment here if you still see it with `rc.4` and we will reopen 👍

**Comment by anhtuan201192** [comment]
I have an issue with the blow version after connecting Trust wallet
    "@walletconnect/ethereum-provider": "^2.7.4",
    "@web3modal/standalone": "^2.4.3",
    
    
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/10590355/efce004c-85aa-4d14-8fab-4eff79920be7)

**Comment by h4ckthepl4net** [comment]
@anhtuan201192 This issue is related to the case, when you call some ethereum method that is not specified in your provider settings. In my case I've tried to sign a message (call "personal_sign" method of Ethereum JSON_RPC api) without specifying "personal_sign" method in the "methods" array of provider settings. So the solution will be to add all methods that you might call to the provider settings. (Be careful, maybe the wallet app that your'e using (TrustWallet in this case) is not supporting all methods that you want)
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/37217105/56627ede-ac7a-4195-87d0-20020267572d)
