### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.message')

### ISSUE THREAD

**Issue by abdulhaseeb4239** [WalletConnect/walletconnect-monorepo#1519]
**Describe the bug**
I am working on wallet connect integration in react-native.
Most of the exceptions I face were fixed in the new 2.0.0-rc.4 release. But
After keeping the app open for a long time after initializing WC connection, I get a crash with this exception 
[TypeError: undefined is not an object (evaluating 'e.message')]

Is this another unhandled error in the package? Any help would be highly appreciated. Thanks

**SDK Version (if relevant)**
"@walletconnect/react-native-compat": "^2.0.0-rc.4",
"@walletconnect/sign-client": "2.0.0-rc.4",
"@walletconnect/utils": "2.0.0-rc.4",

**Comment by abdulhaseeb4239** [comment]
@bkrem any insights on this?

**Comment by clemente-xyz** [comment]
Hi guys. I'm having a very similar error.

I'm having an unhandled exception, which is also generated on `SignClient.init()`, when somewhere in the WS process, `WsConnection` tries to access to `message`.

Debugging in detail the execution of the `init` method, I realised that `e=undefined` when calling the `parseError` method of `WsConnection`:

![Screenshot 2022-11-14 at 14 43 21](https://user-images.githubusercontent.com/9727036/201675670-c0337e18-916b-4c17-8e88-f8bed076ded2.png)

I attach a screenshot of the error and the trace that i can see on the console:

```
ExceptionsManager.js:180 TypeError: Cannot read properties of undefined (reading 'message')
    at parseConnectionError (error.js:50:14)
    at WsConnection.parseError (ws.js:125:36)
    at socket.onerror (ws.js:89:36)
    at WebSocket.dispatchEvent (event-target-shim.js:818:35)
    at WebSocket.js:271:14
    at EventEmitter.emit (_EventEmitter.js:149:33)
    at MessageQueue.__callFunction (MessageQueue.js:414:27)
    at MessageQueue.js:113:12
    at MessageQueue.__guard (MessageQueue.js:365:9)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:112:10)
```

![Screenshot 2022-11-14 at 13 57 33](https://user-images.githubusercontent.com/9727036/201666767-487bfe0d-04fb-4e82-9695-007db7a35248.png)

I followed step by step the [React Native installation](https://docs.walletconnect.com/2.0/javascript/guides/react-native).

My project versions are:

```json
{
  //...
  "dependencies" : {
    // ...
    "react-native": "0.65.1",
    "@walletconnect/react-native-compat": "^2.1.3",
    "@walletconnect/sign-client": "^2.1.3",
    "@walletconnect/utils": "^2.1.3",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "react-native-get-random-values": "^1.8.0",
  }
}
```

Any idea what is happening?

cc @bkrem

**Comment by clemente-xyz** [comment]
looks like the error is on the `event` arg, which does not contain the `error` prop, only `isTrusted: false`, when calling `this.parseError(event.error);`

![Screenshot 2022-11-14 at 14 58 38](https://user-images.githubusercontent.com/9727036/201678527-d4b5dd72-f166-47f9-9520-1b9a3ec64308.png)

**Comment by xwartz** [comment]
+1, I have the same issue.

**Comment by chadyj** [comment]
A common cause of this issue is that the SDK can't connect to the relay. 
In most cases, this is caused by not providing a `projectId`.

https://docs.walletconnect.com/2.0/javascript/sign/installation#1-obtain-project-id

**Comment by ganchoradkov** [comment]
Hey @abdulhaseeb4239 @ClementeSerrano @xwartz this error usually happens when `projectId` is not provided or is invalid during `sign-client` initialization as shown in our [docs](https://docs.walletconnect.com/2.0/javascript/sign/dapp-usage#create-a-session)

If the issue still persist, please provide us with full connection string e.g. full `wss:` so we can investigate possible react native issues 🙏

**Comment by xwartz** [comment]
after upgrading `events` and `AsyncStorage` to the latest version, it works fine.

**Comment by estrattonbailey** [comment]
Just here to +1. Would love to see better error messages for stuff like this, super hard to debug at the moment.

**Comment by earthgohan** [comment]
in react native

`
Core Initilization Success
SignClient Initilization Success
`
but, socket events are not getting emitted with error `undefined is not an object (evaluating 'e.message') `
`
 signClient.on("session_proposal", (event) => {
    console.log(event, "session_proposal");
  });
 signClient.on("session_event", (event) => {
    console.log(event, "session_event");
  });
  signClient.on("session_request", (event) => {
    console.log(event, "session_request");
  });
`

**Comment by biplobsd** [comment]
I have fix this problem by doing this step...
1. Goto your project https://cloud.walletconnect.com
2. Set blank `Allowed Domains` and Save 
![image](https://user-images.githubusercontent.com/43641536/204107647-dbbcee51-9409-4511-94d9-76946a22acf2.png)

3. Reset Project ID and get new one
4. Update your Project ID in your project

**Comment by estrattonbailey** [comment]
Following up, I think this thread may contain some [red herrings](https://en.wikipedia.org/wiki/Red_herring).

Yes, a cryptic error occurs if `projectId` is invalid. I saw similar exceptions for failing to connect to the relay server (we only allow certain HTTP connections in our app). I presume similar errors occur for "Allowed Domains" issues.

But I believe the core reason the logs for these exceptions are unclear and cryptic is because `events` is out of date. I upgraded to latest `3.3.0` and now error logs come through in a more helpful way.

* * *

To help others search for this, here's what I was seeing in the logs before I upgraded.
```
ERROR  {"context": "core"} undefined is not a function
ERROR  {"context": "client"} undefined is not a function
ERROR  [TypeError: undefined is not a function]
```

**Comment by BenjaminPiette** [comment]
Same problem here. The problem is that whenever the websocket gets disconnected, it tries to reconnect in a timeout. But exceptions during connection are not caught, resulting in the described error.

<img width="527" alt="image" src="https://user-images.githubusercontent.com/7567594/206943431-3fad1ef3-6ebb-4188-b114-0a5c13d68610.png">

<img width="737" alt="image" src="https://user-images.githubusercontent.com/7567594/206943462-53baf6d9-4caf-49e8-98f4-b676be585b58.png">

<img width="829" alt="image" src="https://user-images.githubusercontent.com/7567594/206943615-867b25bb-55a8-4da9-920d-31bb3a78ca72.png">


To reproduce, just connect to the relay server, then make your phone into flight mode. This triggers the error almost immediatelly as the stack tries to reconnect and fails.

**Comment by gergana95** [comment]
Same issue on my side but on React, not react-native, happens after computer sleep on localhost. The wss link from the error contains the projectId which is passed on initialization. 

 ```
"react": "^17.0.2",
 "react-dom": "^17.0.2",
 "@walletconnect/sign-client": "^2.1.0",
 "@walletconnect/types": "^2.1.0",
 "@walletconnect/utils": "^2.1.0",
```

<img width="1440" alt="Screenshot 2023-01-13 at 10 09 25" src="https://user-images.githubusercontent.com/29689645/212292973-01915013-04b9-45d1-b098-1c5a02b5fdf5.png">


It seems to happen from this line in ws.js:
 
<img width="795" alt="Screenshot 2023-01-13 at 12 10 29" src="https://user-images.githubusercontent.com/29689645/212294532-37f988aa-13e8-47a3-b4b3-79f2602ec3ba.png">

**Comment by ganchoradkov** [comment]
Hi @gergana95, are you providing projectId during sign initialization? I'm failing to see the param in the connection uri.
Is the socket working before the computer goes to sleep?

Also, please consider updating your client to the latest version (currently 2.2.1)

**Comment by gergana95** [comment]
Hi @ganchoradkov, yes I am providing projectId during sign initialization, the connection uri visible to you is not the whole one, but projectId is actually there right after auth key.

Init looks like this:

```
SignClient.init({
        projectId: 'projectId',
        relayUrl: 'wss://relay.walletconnect.com',
        metadata: {
          name: '',
          description: '',
          url: '',
          icons: ['']
        }
})
```

**Comment by ganchoradkov** [comment]
@gergana95 thanks for the snippet, it looks correct. Is the connection working at all for you or it fails when the computer goes to sleep?

**Comment by gergana95** [comment]
@ganchoradkov Its working properly, only after sleep this happens, currently I got this error also on production, from what I can see the projectId again is inside the url. So there is some kind of issue with init on this version. Which next version would fix this?

**Comment by finessevanes** [comment]
@gergana95 are you still experiencing this issue?

**Comment by glitch-txs** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the latest version :)
