### ISSUE TITLE
Event does not include pairing_delete and pairing_expire

### ISSUE THREAD

**Issue by AlexandrosGounis** [WalletConnect/walletconnect-monorepo#1576]
**Describe the bug**
When deleting `sessions`, a client can listen to `session_delete` events, but this is not the case for pairings.
Type `Event` omits `pairing_*` (all pairing related events)

https://github.com/WalletConnect/walletconnect-monorepo/blob/81785ed7e8922cd149a8320c9a166795fa08196a/packages/types/src/sign-client/client.ts#L9-L18

Is this intentional? I was expecting to be able to listen for pairing events when the get deleted:

```tsx
signClient.on("pairing_delete", () => {
   // listen for pairing deletions
})
```

**SDK Version (if relevant)**
 - Client: v2.1.0

**Comment by bkrem** [comment]
Hi @AlexandrosGounis,

Yes, this indeed changed in the `v2.0.0` stable release, pairings are now managed by the shared [Pairing API](https://docs.walletconnect.com/2.0/javascript/core/pairing-api), rather than by the client directly.

There's a summary of all important changes around pairing in the release notes: https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.0.0

We also added these Info sections in the docs to point people towards pairing-related events:
<img width="902" alt="Screenshot 2022-11-01 at 13 19 10" src="https://user-images.githubusercontent.com/8663099/199230827-edbf3100-c9d8-4db9-866e-d05bb20b55bc.png">

---

Hope that helps, if you encounter issues with pairing-related events/behaviour, please open another issue and we'll investigate 👍
