### ISSUE TITLE
2.1.4 WebSocket connection failed for URL: wss://relay.walletconnect.com

### ISSUE THREAD

**Issue by xpluscal** [WalletConnect/walletconnect-monorepo#1686]
**Describe the bug**
Walletconnect modal doesn't open in 2.1.4 with WSS error:

'WebSocket connection failed for URL: wss://relay.walletconnect.com?auth=...=wc-2%2Fjs-2.1.3%2Fmacos-chrome-107.0.0%2Fbrowser%3A127.0.0.1%3A5174'

The interesting thing here is that the URL tries to get 2.1.3, but package version 2.1.4 is installed.
Note: this is running on localhost (also tried with 127.0.0.1)

**SDK Version (if relevant)**
 - Client: Browser (Chrome)
 - Version 2.1.4

**Comment by ganchoradkov** [comment]
hey @xpluscal , I'm not seeing `projectId` parameter in your URI. [As per our docs](https://docs.walletconnect.com/2.0/javascript/sign/installation#1-obtain-project-id), `projectId` is required to connect to `wss://relay.walletconnect.com`

**Comment by arein** [comment]
@ganchoradkov for your consideration: this will come up again. How about `iff` you're connecting to `walletconnect.com`/`walletconnect.org` AND there's no `projectId` parameter in the URI we immediately throw an error.

Since we're using Websockets it's a bit hard to provide a decent error message when the WS handshake/upgrade fails.

**Comment by xpluscal** [comment]
Hey thanks for the heads up!
Since when is that a requirement? We are running walletconnect embed on multiple sites without a projectID through web3modal working fine.

**Comment by domhhv** [comment]
I had the same issue just recently. Just in case someone is running into this issue too, it turned out that we had [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) set up on our website.

So I managed to solve the issue on my end by enabling CSP's [connect-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src) to `*` on the page where I struggled to open the WalletConnect modal.

**Comment by cguillemette** [comment]
> hey @xpluscal , I'm not seeing `projectId` parameter in your URI. [As per our docs](https://docs.walletconnect.com/2.0/javascript/sign/installation#1-obtain-project-id), `projectId` is required to connect to `wss://relay.walletconnect.com`

The link is broken, can you please share the link again? Thanks!

**Comment by SKALEZ-A** [comment]
> I had the same issue just recently. Just in case someone is running into this issue too, it turned out that we had [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) set up on our website.
> 
> So I managed to solve the issue on my end by enabling CSP's [connect-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src) to `*` on the page where I struggled to open the WalletConnect modal.

how is that done ?
Kindly attach a code snippet or something

**Comment by N55j44s7h8a9** [comment]
[Gamee](url)
