### ISSUE TITLE
Add edeXa Testnet Chain 

### ISSUE THREAD

**Issue by ranjith-edx** [WalletConnect/walletconnect-monorepo#1893]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec :   https://docs.edexa.network/how-to/reference/edexa-api-methods
   **GitHub Link**: https://github.com/devEdexa
   Json-RPC : https://testnet.edexa.com/rpc 
2. **namespaces**: eip:155
3. **chains**: eip155:1995   (testnet)

**Comment by bkrem** [comment]
Hi @ranjith-edx,

Couple of questions:
* Is there also a mainnet?
* Are you aware of wallets actively developing for Edexa?

**Comment by ex-shubham-koli** [comment]
Greetings @bkrem,
Thanks for your quick-response.
At edeXa, we are engaged in the development of a business-oriented blockchain platform. Presently, we have a testnet in operation and anticipate the launch of our mainnet in April. In addition to creating our own wallet application for our decentralized finance projects, we have also established partnerships with several enterprises for the integration of our solution into their existing systems (unfortunately, we are unable to disclose their names due to non-disclosure agreements). Furthermore, we have plans to integrate with Trustwallet following the mainnet launch.

**Comment by ranjith-edx** [comment]
Hi @bkrem  is there any other info needed ..?!

**Comment by Helpcentera** [comment]
> Hi @ranjith-edx,
> 
> Couple of questions:
> * Is there also a mainnet?
> * Are you aware of wallets actively developing for Edexa?

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by ranjith-edx** [comment]
Hi @bkrem  the above @Helpcentera  looks suspecious can you please confirm what it is and what kind of form it is ..?!

**Comment by Helpcentera** [comment]
@ranjith-edx kindly make use of the form to rectify your issue

**Comment by bkrem** [comment]
> Hi @bkrem the above @Helpcentera looks suspecious can you please confirm what it is and what kind of form it is ..?!

@ranjith-edx I have deleted those comments and reported as phishing. We will block the user if it occurs again, thanks for flagging it.

I will re-review this request again later today and add edeXa if good to go.

**Comment by bkrem** [comment]
Added to Cloud 👍
