### ISSUE TITLE
Everscale

### ISSUE THREAD

**Issue by lamarketing** [WalletConnect/walletconnect-monorepo#1904]
**Adding a new chain to the Explorer: EVERSCALE**

1. JSON-RPC spec.
   **GitHub Link**: https://github.com/itgoldio/everscale-walletconnect-jsonrpc
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**: https://github.com/ChainAgnostic/namespaces/pull/52
3. **namespaces**:
   `tvm`
4. **chains**:
   `tvm:42`
5. **RPC endpoints**:
  https://dapp01.itgold.io/graphql
  https://dapp02.itgold.io/graphql
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
   `Ever`
    396 | 0x8000018c | EVER | Everscale

**Comment by bkrem** [comment]
Hi @lamarketing,

Thank you for the request to add Everscale!

Couple of questions:
* The JSON-RPC spec only seems to contain two methods currently: `ever_getAccounts` and `ever_processMessage`. Are these two alone sufficient for all common use cases in a dapp-wallet connection?
* Can you name any wallets or partners that are currently building on Everscale?

**Comment by vvismaster** [comment]
Good evening!

Here are the answers to your questions:
1. Any address in Everscale is a smart contract. The "ever_processMessage" method allows you to call any method of any contract, so this covers all possible situations. If something is missing, then we will supplement our implementation
2. Here are links to other ecosystem projects
- wallets: https://ever.surf/, https://everwallet.net/, https://everspace.app/, other less popular: https://everkit.org/en/coin
- DEX: https://flatqube.io/ 
- Bridge: https://octusbridge.io/
- NFT market: https://grandbazar.io/
- DeNS: https://evername.io/
- List of other projects: https://everkit.org/en/ecosystem

CoinMarketCap: https://coinmarketcap.com/currencies/everscale/

**Comment by bkrem** [comment]
Thanks @lamarketing and @vvismaster 👍 

Requested namespace and chains have been added to Cloud.

**Comment by bkrem** [comment]
Hi @lamarketing, @vvismaster,

I'm reopening here since it seems like the actual CAIP spec PR required for completion has stalled. Original mistake was on me for closing this too early, but we'd really appreciate if you could address @bumblefudge's review comments here: https://github.com/ChainAgnostic/namespaces/pull/52#discussion_r1107046666

CASA specs are where implementers go to learn how to connect in the Everscale ecosystem without bugs. If the CAIP spec doesn't reach consensus/isn't merged, this will result in ambiguity and confusion for implementing devs, and hence bugs.

**Comment by lamarketing** [comment]
Thanks. We answer to @bumblefudge.

**Comment by vvismaster** [comment]
@bkrem 

Please make changes to Wallet Connect: 
- name of group from "Everscale" to "TVM"
- name of network "everscale:mainnet" to "tvm:everscale_mainnet"
- name of network "everscale:devnet" to "tvm:everscale_devnet"

We have already implemented the integration, but we cannot test it, because the previous network name does not pass validation.
`If you correct the names, you will help us a lot.` We have fix it on ChainAgnostic.

**Comment by bkrem** [comment]
cc @Cali93 could you help update the chain/namespace values here pls? 🙏

**Comment by vvismaster** [comment]
@bkrem Please tell me when will it be possible to place documentation for RPC Everscale by analogy with
https://docs.walletconnect.com/2.0/advanced/rpc-reference/tezos-rpc ?

**Comment by bkrem** [comment]
> @bkrem Please tell me when will it be possible to place documentation for RPC Everscale by analogy with [docs.walletconnect.com/2.0/advanced/rpc-reference/tezos-rpc](https://docs.walletconnect.com/2.0/advanced/rpc-reference/tezos-rpc) ?

@vvismaster Feel free to add a PR to the docs repo for Everscale RPC 👍  See [here](https://github.com/WalletConnect/walletconnect-docs/pull/513) for the Tezos one for reference.

Closing here since the original request is resolved and the updates to `tvm` have been applied.

**Comment by finessevanes** [comment]
@vvismaster merged!
