### ISSUE TITLE
Add Armonia Meta Chain into the list

### ISSUE THREAD

**Issue by masterayman** [WalletConnect/walletconnect-monorepo#2158]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **
   * https://docs.amax.network/en/latest/API/AMAX-RPC/
   * https://docs.amax.network/en/latest/API/AMAX-RPC/#wallet-rpc
   
   **GitHub Link**: https://github.com/armoniax
   
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**: same as **EOS** 
   https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-2.md
   
3. **namespaces**:
   same as **EOS** 

4. **chains**:
   _\*known chains, where the primary key is a compound key composed of namespace + reference (e.g. ETH mainnet is eip155:1)._
   _Please provide labels for each chain (e.g. mainnet, testnet, devnet, ...)_
   - mainnet:  same as EOS mainnet
   - testnet:  same as EOS testnet
   - devnet:  same as EOS devnet
   
5. **RPC endpoints**
   _\*list of common/canonical RPC endpoints for the chain(s)_
   - mainnet: https://expnode.amaxscan.io 
   - testnet: http://exp1.nchain.me:18888
   
   
6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**: 1048576
   _\* slip44 coin type used in the namespace_

**Additional context**
We are dev team of https://aplink.app

**Comment by bkrem** [comment]
Hey @masteraychen,

Thanks for proposing Armonia, seemingly a couple of issues here:

* EOS doesn't seem to have a CASA namespace definition yet? cc @bumblefudge to confirm 🙏 
* By extension "same as EOS mainnet/testnet" needs actual values which will be determined by the namespace spec :)

**Comment by bumblefudge** [comment]
Nope, nothing ever merged, but I did try updating [an open PR](https://github.com/ChainAgnostic/namespaces/pull/5) from before I joined CASA. I have never used EOS, much less coded for it, so my contributions are really just guesses from reading the docs-- which is why I hesitate to merge without confirmation from an actual buildor.  

Maybe you could help me finish it up, @masteraychen ? Other than just confirming or updating the existing PR, one thing I'd like to add (the only thing that's really blocking **this** PR is a `Resolution Method` section that tells an unfamiliar, non-EOS wallet and/or dapp how it confirms it's on the chain it thinks it's on by querying the node with an "info" or "hello world" function.  See the following examples for comparison, including 1 or 2 that exist just to say it's currently impossible to confirm:
[algorand](https://namespaces.chainagnostic.org/algorand/caip2#resolution-method) [btc](https://namespaces.chainagnostic.org/bip122/caip2#resolution-method) [eth](https://namespaces.chainagnostic.org/eip155/caip2#resolution-method) [hedera](https://namespaces.chainagnostic.org/hedera/caip2#resolution-method) [polkadot](https://namespaces.chainagnostic.org/polkadot/caip2#resolution-method) [sol](https://namespaces.chainagnostic.org/solana/caip2#resolution-method) [stacks](https://namespaces.chainagnostic.org/stacks/caip2#resolution-method) [starknetv1 - possibly deprecated soon](https://namespaces.chainagnostic.org/starknet/caip2#resolution-method) [stellar](https://namespaces.chainagnostic.org/stellar/caip2#resolution-method) [everscale/tvm](https://namespaces.chainagnostic.org/tvm/caip2#resolution-mechanics) [waves](https://namespaces.chainagnostic.org/waves/caip2#resolution-method) [xrpl](https://namespaces.chainagnostic.org/xrpl/caip2#resolution-method)

**Comment by Narsiss** [comment]
@bumblefudge 
I've submit a draft PR for Armonia Meta Chain(AMAX) in  [namespaces](https://github.com/ChainAgnostic/namespaces/)
https://github.com/ChainAgnostic/namespaces/pull/64

**Comment by bkrem** [comment]
Closing as stale since the CASA PR is still in draft and seems to have stalled.

Feel free to comment here if the namespaces spec is merged in CASA and we can reopen here 👍
