### ISSUE TITLE
Replace EventManager with EventEmitter

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/walletconnect-monorepo#222]
Use the NodeJS module EventEmitter instead of EventManager

**Comment by corydickson** [comment]
From my understanding of how `EventManager` works is that it manages the subscriptions of events from the connector and triggers their callbacks based on the object received that describes the message and corresponding parameters to be used as the payload or error message. Do you think it's best to have the connectors use the `EventEmitter` module directly -- managing their subscriptions etc, or should keep the class's API the same by having `EventManager` use it's existing `subscribe` method to add listeners and then emit corresponding events inside `trigger`.

I'm leaning towards the latter route because other wise the type system would need to be changed for the connector to correctly resolve the messages it creates

**Comment by pedrouid** [comment]
The Client logic needs to split into multiple controllers which each would be EventEmitters extended for different concerns. Currently the EventManager is emitting events for different concerns and routing them according to each type which unnecessary.

I will address this with the v2.0 instead of changing the current v1.0 clients
