### ISSUE TITLE
bug: [Marble Wallet/WalletConnect V2] When trying to sign message the wallet page opens in same tab leaving the app

### ISSUE THREAD

**Issue by aximas** [WalletConnect/walletconnect-monorepo#2303]
I suppose this bug starts from authentication when appear **qr modal** and there **by default** selected **Marble wallet**

**Comment by JesseKuntz** [comment]
I was about to report the same - and it isn't only Marble Wallet, it is any wallet that doesn't have a legit deeplink set. Here's what I've found with the Fireblocks wallet, also tested with Marble wallet (feel free to move this into the description):

When we trigger the `eth_sendTransaction` request, the Fireblocks wallet opens up in the current tab - this is bad, because it closes the dApp and we can no longer wait for the response of the `eth_sendTransaction` request.

This looks to be in WalletConnect’s control. You can see here, they are opening the site in the current tab:

https://github.com/WalletConnect/walletconnect-monorepo/blob/615bf7114a8d1da3bb239c3701fafb4af24e5ec4/providers/universal-provider/src/utils/deepLinks.ts#L36-L38

`deeplinkRedirect` is called in `handleDeepLinks` (same file) and here is where `handleDeepLinks` is called:

https://github.com/WalletConnect/walletconnect-monorepo/blob/615bf7114a8d1da3bb239c3701fafb4af24e5ec4/providers/universal-provider/src/providers/eip155.ts#L50-L53

And since `eth_sendTransaction` is set in `this.namespace.methods`, we go down this path (WalletConnect sets this for us - if we try to unset it, we get an error when we make the request, which makes sense).

If we’re using the Fireblocks wallet, we don’t want this to happen - and it’s confusing, because `WALLETCONNECT_DEEPLINK_CHOICE` (in local storage) is set to [https://console.fireblocks.io/v2](https://console.fireblocks.io/v2), which isn’t a deeplink. 

But when you think about the fact that this is code for deeplinks, it makes total sense - we’d want it to work this way. Take Ledger Live for example - it’s a desktop app, so we’d want to “open” it from our current tab, and it won’t close our current tab. 

> 💡 You can test this by opening any site and in the console, running: `window.open("ledgerlive://accounts", "_self")`

**Here's the workaround that we have for now:**

Right before we trigger the `eth_sendTransaction` request, remove the `WALLETCONNECT_DEEPLINK_CHOICE` from local storage, and then add it back in after we’re done signing and broadcasting. It’d be on the user to go find their wallet and sign the tx, but we’d keep the dApp open. Additionally, we detect if the link is a deeplink or not - if it isn’t, then we can just leave it alone. Then Ledger Live users (or users of any desktop wallet) could have a slightly better/the intended UX.

**Comment by JesseKuntz** [comment]
This is fixed by https://github.com/WalletConnect/walletconnect-monorepo/pull/2869 and IMO can be closed, thanks @0xAsimetriq!
