### ISSUE TITLE
Application inclusion to Wallet Connect 2.0 Ecosystem

### ISSUE THREAD

**Issue by coindex-admin** [WalletConnect/walletconnect-monorepo#2514]
**Adding a new chain to the Explorer**
To get a new chain added to the Explorer, you will need to submit the following:

1. JSON-RPC spec for Wallets **(only if [one](https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc) doesn't already exist)**. For more information, please review the Ethereum [JSON-RPC API docs](https://ethereum.org/en/developers/docs/apis/json-rpc/).
   **GitHub Link**: https://docs.walletconnect.com/2.0/advanced/rpc-reference/ethereum-rpc
2. Write a [CASA namespace spec](https://github.com/ChainAgnostic/namespaces) if not already available for this namespace.
   **GitHub Link**: [EIP-155](https://github.com/ChainAgnostic/namespaces/tree/main/eip155)
3. **namespaces**:
   eip:155 for Ethereum/EVM-based chains
   
4. **chains**:

5. **RPC endpoints**

6. **[SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) coin type**:
  The coin type is 60

**Comment by bkrem** [comment]
Hi @JiunnJyeNg,

Thank you for your submission. Could you please provide the full name of the project and further resources where the WalletConnect team can get a sense of the project (e.g. homepage, docs, etc)?

I've searched for "Coindex" but I'm not finding anything related to a specific blockchain.

**Comment by coindex-admin** [comment]
Thank you for your response in this matter. Coindex is a private chain used by an internal community of users. We are using this chain for our sites accessible by our internal community users only.

May i know what other detail would you need ?

**Comment by coindex-admin** [comment]
Hi Admin, 
Can you advise on the detail and documentation required. I have provided the answer to the list of questions above. 
Thank you

**Comment by JiunnJyeNg** [comment]
Hi Admin, 
I have not receive any responds for my question above. 
Attached below is the whitepaper for coindex, 
[Coindex White Paper.pdf](https://github.com/WalletConnect/walletconnect-monorepo/files/11815736/Coindex.White.Paper.pdf)
Please see you need any other details. 

Thank you 

Rgds,
jay

**Comment by bkrem** [comment]
Hi @JiunnJyeNg,

WalletConnect's stance on this matter is that adding a private blockchain is not of public value, since the blockchain's listed in WalletConnect Cloud should generally be _publicly visible and accessible_.

Ideally any EVM-based/`eip155` chain should also be listed in https://github.com/ethereum-lists/chains, which we may make a requirement moving forward.

Note: Coindex not being added does not alter or inhibit the usability of the WalletConnect protocol with Coindex.

Thank you nonetheless for proposing Coindex, we may re-evaluate in the future if there are compelling reasons to do so.
