### ISSUE TITLE
the scheme does not have a registered handler.

### ISSUE THREAD

**Issue by fooshyangsong** [WalletConnect/walletconnect-monorepo#2629]
**Describe the bug**
When the modal pop up, it only shows select wallet. Click on select wallet will show this error in the console.  I am using google chrome browser.

**To Reproduce**
1. Go to 'https://react-dapp-v2-with-web3js.vercel.app/'
2. Click on  any network, then wallet connect modal should be pop up. Only showing select wallet button.
3. Click select network button and not thing happens
4. See error in console.

react-dapp-v2-with-web3js.vercel.app/:1 Failed to launch 'wc:f796209c3780ff2d8ee1cf0a8f604f395dcece8d122c7749afe9f20db7bda6da@2?relay-protocol=irn&symKey=93f9e8105cd63a8a94b0a8a95c954760e4db8c0d10631377090783bc9c378601' because the scheme does not have a registered handler.

**Comment by bkrem** [comment]
Hi @fooshyangsong,

This is likely because you're previewing the dapp using an Android user agent in a non-Android context.

E.g. I can reproduce this by setting an android device User-Agent in the DevTools, which will prompt Web3Modal to behave as if it's on Android, but then fail to find any app that has registered itself for the `wc:` schema because it's not actually on Android. See the repro below:

<img width="800" alt="Screenshot 2023-06-14 at 21 11 11" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/8663099/8fbc5121-0841-4006-bcbc-903a0b625e15">

### Recommendation

If you use a web/iOS user-agent this is not an issue.

**Comment by AarNtyon** [comment]
Hi bro, my mobile phone is installed with a third-party wallet. when I click the link on the web, it only shows the connected wallet.
