### ISSUE TITLE
[EthereumProvider] Doubling of connected accounts.

### ISSUE THREAD

**Issue by ksamarin90** [WalletConnect/walletconnect-monorepo#2641]
**Describe the bug**
While instantiating EthereumProvider and omitting optional parameter "optionalChains"  like that:
```
const provider = await EthereumProvider.init({
	projectId: 'xxx',
	chains: [1],
	showQrModal: true,
});
```
connected account is doubled in EthereumProvider.accounts like so ```[0x1...2, 0x1...2]```.
It is also doubled while approving connection in TrustWallet (see screenshot below).

If provider is instantiated with "optionalChains" like so:
```
const provider = await EthereumProvider.init({
	projectId: 'xxx',
	chains: [1],
        optionalChains: [100500],
	showQrModal: true,
});
```
EthereumProvider.accounts shows correct value ```[0x1...2]```.

**To Reproduce**
See above.

**Expected behavior**
If "optionalChains" are not passed to init method there is no doubling of connected accounts.

**Screenshots**
Screen in TrustWallet during connection.
![IMAGE 2023-06-15 12:36:10](https://github.com/WalletConnect/walletconnect-monorepo/assets/60395970/dcae7ede-93eb-45ae-915b-f2022612d4d2)

According to code https://github.com/WalletConnect/walletconnect-monorepo/blob/f78425a6116b692e9463ecb552ee870f29bd476b/providers/ethereum-provider/src/EthereumProvider.ts#L185 it seems to be the problem that "optionalChains" while being an optional parameter has a default value of ```[1]```.

**Comment by bkrem** [comment]
@ksamarin90 thanks for the report.

Could you please provide the exact version of `EthereumProvider` you're seeing this with?

I've tried to reproduce [here](https://github.com/WalletConnect/web3modal/commit/9e322ac4492c07d0af2fec95f66266bbb9c58b7a):
* interestingly I do see the duplicated accounts artefact in Trust
* but I only ever see a single account with the standard `chains: [1]` config (no `optionalChains`) post-connect

cc @ganchoradkov

**Comment by ksamarin90** [comment]
Hi @bkrem, the version is 2.8.0.

**Comment by ksamarin90** [comment]
@bkrem I check it this way:
```
provider.on('accountsChanged', accounts => {
	console.log(accounts);
});
```
and I see two accounts....

**Comment by JonathanConn** [comment]
@ksamarin90 Thanks for letting us know <3 
When I attempted to repro the issue, I was not able to see duplicate accounts in the provider

This is what I think is happening: 
The reason you see two accounts in Trust wallet is because Trust wallet displays both the required and optional namespaces

So if I was to change the optional chain to polygon, in trust wallet, you would see
Wallet 1
Eth
Wallet 1
Polgon 

Which I understand can be confusing, but the accounts are not actually being duplicated 
Many other wallets I tried (Rainbow, MM, Zerion) did not display the optional namespaces 

We are in the process of changing our default for `EthereumProvider`, you can check it out [here](https://github.com/WalletConnect/walletconnect-monorepo/pull/2781)

I also checked the provider using the `accountsChanged` event you tried, and I only saw one account

If you have any other questions or concerns, feel free to reach out, thanks!

**Comment by bkrem** [comment]
@ksamarin90 as Jon noted, we don't seem to be able to reproduce with `EthereumProvider` directly.

If you can provide us a with a minimal reproduction of your case we'll keep digging 👍
