### ISSUE TITLE
error when trying to load the @walletconnect/web3-provider lib in an iframe

### ISSUE THREAD

**Issue by ramirotw** [WalletConnect/walletconnect-monorepo#289]
I'm building a dApp which uses the `@walletconnect/web3-provider` lib indirectly. Locally and during testing everything works great, the issue comes when I deploy the app as it gets executed in an iframe:

```
main.js:formatted:134093 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

I traced back the exception to the [storage](https://github.com/21paradox/cfx-walletconnect/blob/51a84576d6b5ba066c6db16520c9a2697c98d1d7/packages/cfx-walletconnect-client/storage.ts) utility class of this monorepo.

I believe the problem comes from this [part](https://github.com/WalletConnect/walletconnect-monorepo/blob/next/packages/helpers/utils/src/browser.ts#L44):

```js
export function unsafeGetFromWindow<T>(name: string): T | undefined {
  let res: T | undefined = undefined;
  if (typeof window !== "undefined" && typeof window[name] !== "undefined") {
    res = window[name];
  }
  return res;
}
```
As that is compiled down to:

```js
"undefined" != typeof window && void 0 !== window.localStorage && (a = window.localStorage),
```

Which ends up throwing the exception.

**Comment by pedrouid** [comment]
which version are you using? Can you try version `1.0.0-rc.4`?

**Comment by ramirotw** [comment]
@pedrouid The lib was using `1.0.0-beta.47`, I bumped it to `1.0.2` but nothing changed, same error.

Would be possible to wrap this in a try...catch?

```js
export function unsafeGetFromWindow<T>(name: string): T | undefined {
  let res: T | undefined = undefined;
  try {
    if (typeof window !== "undefined" && typeof window[name] !== "undefined") {
      res = window[name];
    }
  catch (e) {
    console.log(e);
  }
  return res;
}
```

**Comment by pedrouid** [comment]
Need to test this. Why wouldn't localStorage be available? It's would be quite important for browser usage in the case of WalletConnect

**Comment by joshstevens19** [comment]
Safari blocks storing anything in local storage within an iframe. web3 use to use local storage without try catching it and this did not allow you to be able to use web3 in an iframe supporting every browser. A try-catch will solve this but if the lib needs local storage it should probably look into the new storage API which safari now supports - https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API to allow this to support iframes in safari (which quite a lot of wallet integrations would be using to add protection between cross-site domains and holding the private key in memory without the integrator being able to get to it).

**Comment by tms1337** [comment]
@joshstevens19 In my experience, Safari does not block storing in localStorage for iframe, but rather treats the domain and iframe as having separate localStorages

I circumvented this by using `postMessage` between iframe and the domain to pass the content of localStorage back and forth.

**Comment by joshstevens19** [comment]
@tms1337 i don’t think that’s true it blocks third party stuff including cookies and local storage which are the default settings on Safari IOS (unless you change the safari default settings). You can’t set or get from the iframe domain aka actually just in the iframe say the iframe is a different domain and a separate app.  

If your using post message your actually using the patent window to store and set local storage which in most cases you want local storage to be protected to the domain it sets on not the parent.

**Comment by tms1337** [comment]
@joshstevens19 What I mean is that you can do `localStorage.setItem` within an iframe, but it does not get reflected in the domain

But you can open a new window with the domain and then use `postMessage` to communicate with it the storage content

At least that's for the case when you have some sort of popup for authentication

**Comment by pablofullana** [comment]
initially reported issue was in fact found using Brave (w/ shields enabled) when loading the library from within an iframe.

**Comment by wswarren12** [comment]
Having the same issue using Chrome when dApp is deployed using Vercel. Any answers on how to fix without breaking WalletConnect?

**Comment by finessevanes** [comment]
Hey @ramirotw, @wswarren12 are either one of you still experiencing this issue?

**Comment by koskotheim** [comment]
@finessevanes 

We are still experiencing this issue in the event that the browser blocks third-party cookies and the app is loaded in an iframe. This can happen in chrome, safari, brave, etc, depending on the browser preferences. It is an issue because we can't control users' browser preferences, and as it stands currently, it will break because the above reference to localStorage is not in a try / catch. 

We have tried detecting this situation and using a global proxy for local storage on the window object to try / catch any calls on local storage. That fixes this particular issue but breaks other things that do handle but expect an error if local storage is not available. 

We are using version 2.7.0 of @wagmi/connectors, which depends on version 2.8.2 of @walletconnect/ethereum-provider

Here is a minimal example to demonstrate: 
https://wallet-connect-embed-example.web.app/

```html
<!DOCTYPE html>
<html>
  <body>
    <iframe
      src="https://example.walletconnect.org/"
      style="position: absolute; top: 0; left: 0; width: 100vw; height: 100vh"
    >
    </iframe>
  </body>
</html>

``` 

The above site will work fine until you go into browser preferences and disable third party cookies. Then it will not work and will just throw that error about local storage. 

![Screen Shot 2023-09-14 at 9 12 53 PM](https://github.com/WalletConnect/walletconnect-monorepo/assets/98971550/44018460-f0e7-445c-8cf2-1b88b11f36bc)
