### ISSUE TITLE
UI Styling bug on mobile safari 

### ISSUE THREAD

**Issue by ianlapham** [WalletConnect/walletconnect-monorepo#296]
issue: some styling bugs in the wallet options modal using @walletconnect/qrcode-modal

environment: iOS safari 

replicate: try to login on mobile, click wallet connect - should see some misalignment on the top for closing the modal 

deploy: https://uniswap-frontend-git-fork-ianlapham-v2.uniswap.vercel.app/swap

![image](https://user-images.githubusercontent.com/17100331/85178155-a71c9a80-b232-11ea-9056-6ebaecd070c3.png)

**Comment by pedrouid** [comment]
Thanks for sharing a deployed preview 🙏 The styling issue is caused because two qrcode modals are being rendered which in turn creates two conflicting stylesheets. 

Also noticed that after closing both modals that Uniswap is rendering another custom qrcode underneath.

Make sure you are only instantiating one web3-provider at a time and not calling `enable()` in parallel. 

I will look into how to ensure only modal gets rendered at a time but the quickest fix would be to find the duplicate providers on your side.

**Comment by ianlapham** [comment]
Yep checked this out that seems to be the issue - probably just requires tweaks on our end I will test some things

**Comment by pedrouid** [comment]
Fixed on 1.0.10
