### ISSUE TITLE
getting error unhandled runtime  "wcm-button"

### ISSUE THREAD

**Issue by SumiBisht** [WalletConnect/walletconnect-monorepo#2967]
### Discussed in https://github.com/orgs/WalletConnect/discussions/2966

<div type='discussions-op-text'>

<sup>Originally posted by **SumiBisht** July  3, 2023</sup>
Hey I am using walletconnect eth-provider but sometimes out of nowhere i am getting this error.
Unhandled Runtime Error
NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "wcm-button" has already been used with this registry
<img width="770" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/40060905/28dcd0fb-7f28-4ab0-bd96-6b8492c7f91d">
</div>

**Comment by Soham-ent** [comment]
Hi there, I've encountered this error as well. Upon debugging, I discovered that the component we are using to connect walletconnect is duplicated on some pages. This was because I wanted to prevent users from accessing certain components without being connected to their wallets. I found that the issue was resolved when I removed the duplicate components.

**Comment by SumiBisht** [comment]
Thanks for your reply
