### ISSUE TITLE
Session proposal not working if Dapp and web3Wallet are hosted on same host and port

### ISSUE THREAD

**Issue by johnnyleejy** [WalletConnect/walletconnect-monorepo#2975]
**Describe the bug**
I have a mock dapp implemented using `EthereumProvider` and a wallet implemented using `Web3Wallet`.

Both are implemented in the same application and hosted on locahost:3000.

When I copy the uri of the mock dapp and pair with my wallet, the session proposal always fails. 

It has something to do with how local storage is used for reading and writing by wallet connect.

More details in: https://github.com/orgs/WalletConnect/discussions/2868

**To Reproduce**
1. Clone the wallet connect web examples [fork](https://github.com/johnnyleejy/walletconnect-web-examples/tree/main/wallets/react-web3wallet).
2. Build it
3. Click on 'Connect' button below Mock Dapp
4. Copy and paste uri into the uri input field
5. Press 'Connect'

**Expected behavior**
Session proposal should work and Dapp should be able to connect to wallet on same host and port.

**Screenshots**

**Non working example**
https://github.com/WalletConnect/walletconnect-monorepo/assets/108564365/e3da2879-967a-4c7c-aa72-aa401f626e54

**Working example (after clearing localstorage and refreshing)**

https://github.com/WalletConnect/walletconnect-monorepo/assets/108564365/01ce3036-0fd6-414a-bbc3-172cd224dd3f

**Desktop (please complete the following information):**
Chrome Version 114.0.5735.198 (Official Build) (arm64)

**Comment by glitch-txs** [comment]
This should be fixed in the latest versions, please update all packages and let us know if the issue still persists.

**Comment by SebasAran16** [comment]
Hello, I am facing the same issue with `@web3modal/ethers": "^3.5.7`. Which was released a month ago, is this a behavior that is solved on v4? Thanks!

**Comment by SebasAran16** [comment]
Hello, I am using `@web3modal/ethers": "^3.5.7` to do a similar mock implementation with Smart Contracts on Sepolia. I am having the same issue as in the `Non working example video`.

I tried to erase the local storage as shown, however I can not get the proposal to be sent. I have no problem with others dapps/mobile. But in the same host port I am not getting into the function triggered when receiving a proposal, meaning that I am not receiving a connection proposal at all.

As I understand the version `3.5.7` was launched after this post, meaning it should be the `latest versions` expected to work, am I wrong? Otherwise I would take as an option the implementation of `@web3modal/ethers/v/4.0.9`.

Will be awaiting for any response, thanks!
