### ISSUE TITLE
rename walletconnect react native package

### ISSUE THREAD

**Issue by shahbhavir** [WalletConnect/walletconnect-monorepo#3]
WalletConnect react-native sdk is **not dependent** to react-native platform. The sdk's indirect dependency is `crypto` (a node built-in module) via `walletconnect-core` and firebase in-app messaging. So, whenever any environment (be it [PWA](https://developers.google.com/web/progressive-web-apps/) or mobile app) has access to these dependencies, the developer of these platforms (PWA or mobile app) can use this sdk.
The names could be changed to something like: 
- walletconnect-core (unchanged)
- rn-walletconnect to walletconnect-listener (the app/web-app which will store credentials)
- walletconnect to walletconnect-client (the web/app which will act as a client to communicate with listener sdk)

**Comment by pedrouid** [comment]
Technically it's a 2-way communication so both the client/app/dapp and the wallet will listen, so I wouldn't call it listener.

There will be a lot of renaming in the future, specially when we move into a multi-wallet integration but I would maybe just change `rn-walletconnect` to `walletconnect-wallet` and keep the client library as `walletconnect` because this will be the most widely used library.

There may be 5-10 wallets but there will be 1000s of dapps, so this needs to be intuite to install by running `npm install --save walletconnect` or `yarn add walletconnect`

What I would like to do instead is have multiple versions of walletconnect client library that include different levels of features:

full featured = `import WalletConnect from 'walletconnect'`
lite version = `import WalletConnect from 'walletconnect/lite'`
widget version = `import WalletConnect from 'walletconnect/widget'`
multi wallet = `import WalletConnect from 'walletconnect/multi-wallet'`
custom wallet = `import WalletConnect from 'walletconnect/custom-wallet'`

cc @ligi @jdkanani @jinchung @Dobrokhvalov @vikmeup @localethereumMichael

**Comment by pedrouid** [comment]
Discussion to be followed on: https://discuss.walletconnect.org/t/renaming-javascript-libraries/73
