### ISSUE TITLE
Sepolia Testnet Chain Support

### ISSUE THREAD

**Issue by narinder9** [WalletConnect/walletconnect-monorepo#3021]
Please add support for ETH Sepolia TESTNET chain inside WalletConnect, You can find more details about it at here - https://github.com/eth-clients/sepolia

**Comment by bkrem** [comment]
Sepolia is now selectable on https://cloud.walletconnect.com 👍

To clarify: **this does not influence WalletConnect's support of Sepolia or any specific chain**. WalletConnect v2 is by default multi-chain and agnostic to any particular chain being agreed for a session between a wallet and a dapp.

**If you're seeing that attempts to use Sepolia are failing, this usually means that the wallet has not signalled support for the chain**

**Adding chains to https://cloud.walletconnect.com simply makes them visible and selectable for wallets and dapps in order to be discoverable for a specific chain in https://walletconnect.com/explorer and in Web3Modal (see https://web3modal.com/)**.

**Comment by Xoulomon** [comment]
Thanks @bkrem  your reply is highly insightful
