### ISSUE TITLE
Need support about browser schema in `session_request` event

### ISSUE THREAD

**Issue by bdtren** [WalletConnect/walletconnect-monorepo#3023]
**Describe the bug**
Hi,
I'm working on upgrade my wallet App  SDK from v1 to v2,  from `@walletconnect/client` to `@walletconnect/web3wallet`. And currently I'm stuck in issue that:
1- Open a DApp web page open on browser(Chrome App, or Safari App, ...) request connection, and select My App in the list
2- In My start the paring function, observe `session_request` event and Approve the connection
3- Cannot get the sheme to navigate back to browser App

cannot navigate back to Browser App from my Wallet 

Back then when I used `@walletconnect/client`, there is a `peerMeta.scheme` that I can use it to linking back to browser:

```
walletConnector?.on('web3wallet', (error, payload) => {
    if (error) {
         // Show error
          return;
    }
  
   const { peerId, peerMeta, chainId } = payload.params[0];

   const imageUrl = peerMeta?.icons?.[0];
   const dappName = peerMeta?.name;
   const dappUrl = peerMeta?.url;
   const dappScheme = peerMeta?.scheme; // => Browser scheme is here
}
```

Now with `@walletconnect/web3wallet` and 'web3wallet' event, I couldn't found any scheme field anymore.

Could you guys please help me out with that, thank you very much!

**Comment by ganchoradkov** [comment]
Hey @bdtren, you can access the peer metadata from the session `session.peer.metadata.redirect` prop

**Comment by bdtren** [comment]
Hi @ganchoradkov ,
I Checked that field, and also checked the `peerMetadata` in the result of `core.pairing.pair({ uri })` but they both not having scheme field. while redirect filed is empty

**Comment by Justkant** [comment]
Hi, we have the same issue at Ledger when trying to use the `metadata.redirect` field but it's always empty when coming from the browser

Tested on my browser, in the electron app, on iOS simulator and Android simulator
Using https://react-app.walletconnect.com/, https://lab.web3modal.com/library/wagmi/ and other real dApps

The only time it was populated was when using a native dApp like opensea android app

Is this an expected behaviour ?
