### ISSUE TITLE
walletconnect provider can't be used in frontends

### ISSUE THREAD

**Issue by fritzschoff** [WalletConnect/walletconnect-monorepo#308]
when imported, building your javascript code fails because he can't find some node modules like `keccak` 
reproducing steps.
install walletconnect/provider from npm
import it and try to init.
This should give you an error message

**Comment by pi0neerpat** [comment]
It's working fine for me. What version are you using?

**Comment by fritzschoff** [comment]
The latest. V1.7

**Comment by pedrouid** [comment]
There must be some misunderstanding... the latest is v1.0.13

https://www.npmjs.com/package/@walletconnect/web3-provider

**Comment by fritzschoff** [comment]
Ah sorry, I was referring to we3modal. Yes the walletconnect provider is, as @pedrouid said 1.0.13. But the error stays the same. 
```
ERROR in /home/---/code/fritzschoff/node_modules/keccak/lib/api/shake.js
Module not found: Error: Can't resolve 'stream' in '/home/---/code/fritzschoff/node_modules/keccak/lib/api'
```
same with keccak and cipher-base.
Happens with just a simple in put. 
`import WalletConnectProvider from "@walletconnect/web3-provider";`

**Comment by pedrouid** [comment]
Please open an issue on [web3modal](https://github.com/web3modal/web3modal)
 so that we can discuss it there

**Comment by fritzschoff** [comment]
I don't think this issue originates from web3modal. This is lib seems fine.

**Comment by pedrouid** [comment]
You need to share a bit more about your environment to debug this because you must understand that WalletConnect libraries are used in over 50 applications in production and Web3Modal around 20 applications in production. So the libraries are distributed to be usable in frontends

If stream can't be resolved with your bundler configuration then you should polyfill it or just assign it to be an empty object

For example if you are using WebPack you can do the following in `webpack.config.js`:
```js
const path = require("path");

module.exports = {
  // ...
  node: {
    stream: "empty",
  },
};
```

If you are not using Webpack then you need to read the documentation for your bundler library
