### ISSUE TITLE
Security improvement: Replace stablelib with audited noble libraries

### ISSUE THREAD

**Issue by paulmillr** [WalletConnect/walletconnect-monorepo#3084]
noble cryptography (https://paulmillr.com/noble/) is a high-security, auditable set of contained cryptographic libraries with following features:

- No dependencies, protection against supply chain attacks
- Auditable TypeScript / JS code
- Supported on all major platforms
- Releases are signed with PGP keys and built transparently with NPM provenance

Furthermore, noble-hashes were created with a grant by Ethereum Foundation. hashes and curves have been independently audited by 3rd party entity.

You have following deps:

https://github.com/WalletConnect/walletconnect-monorepo/blob/4ee518cf58b7aa0c59289999e7443918b9d14706/packages/utils/package.json#L33-L38

They can be replaced with:

```json
"@noble/ciphers": "0.1.3",
"@noble/curves": "1.1.0",
"@noble/hashes": "1.3.1",
```

The usage is as following:

```js
import { chacha20poly1305 } from "@noble/ciphers/chacha";
import { hkdf } from "@noble/hashes/hkdf";
import { sha256 } from "@noble/hashes/sha256";
import { x25519 } from "@noble/curves/ed25519";
import { randomBytes as random } from "@noble/hashes/utils";
```

**Comment by paulmillr** [comment]
I assume this repo is unmaintained and you don't really care, since there was no response for 2.5 months (#2272)


@pedrouid @ganchoradkov @0xAsimetriq @bkrem

**Comment by hazae41** [comment]
Sad to see no response to this

I will build a custom WalletConnect lib, it will include adapters for Noble, WebAssembly and Stablelib so you will be able to choose which one you prefer (and you will be able to do it at runtime, e.g. depending on the user connection speed, tradeoff performances against bundle size)

By the way, it will also support arbitrary transport protocols like WebSocket-over-Tor instead of only native WebSockets

EDIT: this might explain why this issue is ignored
<img width="500" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/4405263/54c427e3-9482-42a8-85af-b5cc9f75c15a" />

**Comment by pedrouid** [comment]
Hi @paulmillr @hazae41, can you guys chill out?

I have no connection to StableLib whatsoever 😅 so no need to start conspiracies just because I have one-line commit correcting a typo inside a comment: https://github.com/StableLib/stablelib/commit/cad7e89f9b4df831babc0342f17d1508c31a604e

Now it's important to note that my time in the last 18 months has not been spent coding or reviewing PRs so you are trying to reach out to the wrong guy

Also I follow both of you on Twitter and my DMs are open plus I've followed @paulmillr work since you started writing the Noble cryptography library

So I'm not committing to switch cryptography libraries in this thread but I promise you that I will ask the Javascript team to investigate the pros and cons

Give us some time to evaluate this and we can connect to discuss 

<img width="617" alt="Screenshot 2023-09-15 at 14 42 28" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/10136079/d43946d2-d657-45fe-8861-4cc0d96fe191">

Finally we take security very seriously but this comment above is not the right away to approach it and it just makes your argument weaker

**Comment by hazae41** [comment]
Hey Pedro, 

Sorry my brother if I sounded attackful, you guys are doing great work, and I think we all understand you don't have many time to improve everything

We both take security very seriously, and this is sad to see no response to such improvement proposal; in fact, we would have understood a response that doesn't fit our vision, even a "No, we don't have time" would have been great for us

Keep up the good work ☀️

**Comment by paulmillr** [comment]
Exactly — the issue is response time, which is 5 months at this point. The same reason makes angry security researchers drop 0days in public, without responsible disclosure.

**Comment by paulmillr** [comment]
@pedrouid 

>So I'm not committing to switch cryptography libraries in this thread but I promise you that I will ask the Javascript team to investigate the pros and cons

>Give us some time to evaluate this and we can connect to discuss

When can we expect a response from the team?

**Comment by paulmillr** [comment]
@pedrouid ?
