### ISSUE TITLE
Does not support latest version of Web3Modal Sign V2. Your Project ID is approved and Explorer is an optional step if you would like to have your project marketed on our homepage so that you can get a wider outreach and help users find your dapp. Docs to help you migrate to Sign V2: https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/dapps/dapp-checklist"

### ISSUE THREAD

**Issue by 1648045459** [WalletConnect/walletconnect-monorepo#3377]
**Describe the bug**
When applying for a project ID in https://cloud.walletconnect.com/app, why does the following error appear and the application fails:

Changes requested

Your update has been rejected. Reason:

""Does not support latest version of Web3Modal Sign V2. Your Project ID is approved and Explorer is an optional step if you would like to have your project marketed on our homepage so that you can get a wider outreach and help users find your dapp. Docs to help you migrate to Sign V2: https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/dapps/dapp-checklist""

**SDK Version (if relevant)**
  "@walletconnect/encoding": "^1.0.1",
    "@walletconnect/qrcode-modal": "^1.7.8",
    "@walletconnect/sign-client": "^2.0.0-rc.4",
    "@walletconnect/types": "^2.0.0-rc.4",
    "@walletconnect/utils": "^2.0.0-rc.4",

**To Reproduce**
1. Apply for projectID in https://cloud.walletconnect.com/app
2. Fill in the tab "Explorer" content and submit
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
<img src='https://raw.githubusercontent.com/1648045459/File/master/picture088-1.png'>

**Comment by JeroldG** [comment]
Hi there, 

You do not need to apply for a Project ID as this is pre-approved when you create a new project. We recommend to use your project ID for integration and testing, once you have completed your tests, you may submit an explorer listing as an optional step.

The reason for rejection email is because we were unable to verify that Sign SDK is integrated correctly with your project. This check is required if you wish to have your project published on our homepage explorer.walletconnect.com OR on Web3Modal (required for wallets)., 

 IF you could send me your project ID, I can have a look and run manual tests for you. 

Best,
Jerold
