### ISSUE TITLE
Does not open universal link in new tab

### ISSUE THREAD

**Issue by jafri** [WalletConnect/walletconnect-monorepo#356]
When opening a universal link, it opens it in the same tab as the current application (doing Safari<>Mobile app). In case the user does not have the app installed or in case the user is in a private window, this will replace the current tab with the data.

Fix: Open the universal link in a new tab using target="_blank"

**Comment by finessevanes** [comment]
OP was able to resolve issue.

**Comment by kpyszkowski** [comment]
I managed to resolve the issue under [RainbowKit's WalletConnect connector](https://rainbowkit.com/docs/custom-wallet-list#walletconnect) configuration. 

My objective was to add [`qrModalOptions.desktopWallets`](https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/providers/ethereum-provider/src/types.ts#L111) entry. It accepts both `links.native` and `links.universal`.
By analysis of modal source code it turns out [the URL opens with `target="_blank"` attribute when it is the universal link](https://github.com/WalletConnect/modal/blob/0fb36833dbd9c896940a3c65485049e56ad5f018/packages/modal-ui/src/views/wcm-web-connecting-view/index.ts#L28C5-L31C6).

So the snippet given below makes it working:
```ts
import { walletConnectWallet } from "@rainbow-me/rainbowkit/wallets"

// ...

walletConnectWallet({
  projectId,
  options: {
    qrModalOptions: {
      desktopWallets: [
        {
          id: "foo-bar",
          name: "Foo Bar",
          links: {
            native: "", // Empty string is required
            universal: "https://foo.bar",
          },
        },
      ],
    },
  },
})
  
```
