### ISSUE TITLE
How to reset project Id

### ISSUE THREAD

**Issue by ghost** [WalletConnect/walletconnect-monorepo#3669]
**Describe the bug**
 I'm getting this error after verifying my domain in wallet connect: `Error: WebSocket connection closed abnormally with code: 3000 (Authorization error: Project ID is missing)`, how do you reset the projectId?

I was following this github issue: https://github.com/WalletConnect/walletconnect-monorepo/issues/1744
and resetting worked for him

Using wallet connect via wagmi

**Expected behavior**
No error

**Screenshots**
<img width="778" alt="image" src="https://github.com/WalletConnect/walletconnect-monorepo/assets/143105037/77236334-e643-473f-ae81-7afe43523c77">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 117.0.5938.88

**Comment by GAEAlimited** [comment]
Resetting a project ID typically involves generating a new unique identifier for your project. The exact steps to reset a project ID can vary depending on the service or platform you are using. Below, I'll provide some general steps that you can follow:

Access Your Project: Log in to the platform or service where your project ID is used. This is typically a developer dashboard or control panel associated with the service you are using.

Locate Project Settings: Look for a "Project Settings" or "Project Configuration" section within your developer dashboard. The exact location of this section can vary from service to service.

Generate a New Project ID:

In many cases, you'll find an option to generate or reset the project ID within the project settings.
Click on the option to generate a new project ID or reset the existing one.
Some platforms may allow you to simply edit the existing project ID to a new value.
Save Changes: After generating or updating the project ID, make sure to save the changes within the project settings.

Update Your Application: If your project ID is used in your application's configuration files or code, you'll need to update your application to use the new project ID. Make the necessary changes to your code or configuration files to reflect the updated project ID.

Test Your Application: After updating the project ID in your application, thoroughly test your application to ensure that it functions correctly with the new project ID.

Deploy Changes: If your application is deployed on a web server or hosted on a platform, make sure to deploy the updated version of your application with the new project ID.

Monitor and Debug: Keep an eye on your application to ensure that it's working as expected with the new project ID. If you encounter any issues, use debugging and monitoring tools to identify and resolve them.

Documentation Updates: If your project ID is referenced in any documentation or user guides, be sure to update that documentation to reflect the new project ID so that users are aware of the change.

Communicate Changes: If your project ID is associated with a service that other developers or team members use, communicate the change to them so that they can update their configurations and code accordingly.

Remember that the specific steps and terminology can vary depending on the service or platform you are using. Be sure to consult the documentation or support resources provided by the service for more detailed instructions on resetting or updating project IDs in your specific context.

**Comment by ghost** [comment]
Hey @GAEAlimited, thanks for the detailed response. I just have the project id set up in https://cloud.walletconnect.com/app, and I'm trying to use it via wagmi's WalletConnectConnector. Is there a way to reset the project id from the walletconnect dashboard?

**Comment by ganchoradkov** [comment]
hey @briantuu, this error means `no projectId` was set at all during client initialization. Please check your init params that you're passing correctly the projectId https://wagmi.sh/core/connectors/walletConnect#usage

**Comment by ghost** [comment]
hi @ganchoradkov, the projectId should be properly set via our environment vars. https://github.com/WalletConnect/walletconnect-monorepo/issues/1744 This issue suggests the error may be indicating otherwise
