### ISSUE TITLE
Session cleanup

### ISSUE THREAD

**Issue by chaitanyapotti** [WalletConnect/walletconnect-monorepo#3709]
**Describe the bug**
A wallet and a dapp are connected successfully.
User disconnects the session from Wallet.
User then reloads the dapp and tries to re-connect to wallet.
`signClient.connect()` never resolves in the dapp.

**SDK Version (if relevant)**
 - Client: JS
 - Version 2.10.1

**To Reproduce**
A wallet and a dapp are connected successfully.
User disconnects the session from Wallet.
User then reloads the dapp and tries to re-connect to wallet.
`signClient.connect()` never resolves in the dapp.

Steps:
- Go to https://demo-app.web3auth.io
- Click on `Connect with Wallet` button
- Click on QR Code to copy the wallet connect uri
- Go to any wallet (eg: https://app.tor.us) and connect via wallet connect
- In app.tor.us, click `Use wallet connect` button
- Paste the wallet connect uri and click connect.
- wait for connection to succeed.
- Now, disconnect from app.tor.us
- Reload demo-app.web3auth.io
- Click on `Connect with Wallet` button
- It's now stuck in load (because signClient.connect() doesn't resolve)

**Expected behavior**
signClient should resolve after connection.
deleting the localStorage key manually `wc@2:client:0.3//session` resolves the issue

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 116

**Additional context**

**Comment by ganchoradkov** [comment]
hey @chaitanyapotti I'm able to reproduce the issue on your demo app but I'm not able to point where/why the issue is happening without looking at the source of your implementation. 
The error in the console is 
```ts
modal.esm.js:477 Error while connecting to adapter: wallet-connect-v2 TypeError: Cannot read properties of null (reading '__v_isRef')
    at Object.get (baseControllers.esm.js:313:14)
    at Ve (vue.runtime.esm.js:1146:22)
    at y.get [as _providerEngineProxy] (vue.runtime.esm.js:928:20)
    at get provider [as provider] (baseProvider.esm.js:40:17)
    at get provider [as provider] (noModal.esm.js:37:38)
    at Gt.connectTo (noModal.esm.js:126:17)
    at async Rt.<anonymous> (modal.esm.js:474:7)
```  
It seems the error originates within `modal.esm.js` where we have no control over. 

Could you share a repo where we could reproduce and figure out where the issue is please?

**Comment by chaitanyapotti** [comment]
Here's the adapter: https://github.com/Web3Auth/web3auth-web/blob/master/packages/adapters/wallet-connect-v2-adapter/src/walletConnectV2adapter.ts

Here's the modal code: https://github.com/Web3Auth/web3auth-web/blob/master/packages/modal/src/modalManager.ts

All of this is open-source. Demo App: https://github.com/Web3Auth/web3auth-web/tree/master/demo/vue-app/src

Wallet code: https://github.com/torusresearch/torus-website/blob/develop/src/controllers/walletconnect/WalletConnectV2Controller.js

**Comment by ganchoradkov** [comment]
thanks @chaitanyapotti, I managed to reproduce the issue and found that the actual bug was reported in https://github.com/WalletConnect/walletconnect-monorepo/issues/3693 and is solved in this PR https://github.com/WalletConnect/walletconnect-monorepo/pull/3731

The fix is not yet released but ETA - by end of week
