### ISSUE TITLE
Prefer `opts.connectorOpts.clientMeta` over `getClientMeta`

### ISSUE THREAD

**Issue by desfero** [WalletConnect/walletconnect-monorepo#409]
Right now if you provide `clientMeta` during `Connector` creation 
```
const connector = new WalletConnect({
              uri,
              clientMeta: {
                description: "Neufund App",
                url: "https://neufund.org",
                icons: ["https://walletconnect.org/walletconnect-logo.png"],
                name: "Neufund",
              },
            });
```
they are not taken into account for web-based wallets and the output of `getClientMeta` is used instead which is misleading and for our use case is breaking our e2e tests for wallet-connect flow.

Would be good to always prefer `opts.connectorOpts.clientMeta` when available over `getClientMeta`.

The line in the code that's causing a problem:
https://github.com/WalletConnect/walletconnect-monorepo/blob/7d5acb729d75436773c93be92f02867237393f08/packages/clients/core/src/index.ts#L116

**Comment by pedrouid** [comment]
well that was actually done purposefully and we only added connectorOpts.clientMeta for react-native platform

**Comment by desfero** [comment]
So there is no way to force `clientMeta` provided to the `Connector`?

**Comment by pedrouid** [comment]
Technically you can override it under the private variable `_clientMeta`

**Comment by cloudhead** [comment]
It would be good to have an official way of doing this, because currently it picks up the favicon, which is designed to be a tiny icon, whereas the clientMeta icon is often shown much bigger on mobile. So you can't have a single icon that works for both browsers and mobile, or it'll look blurry on one or the other.

It seems like even in the browser environment, the typechecker allows `clientMeta` to be set as an option, even though it's ignored..
