### ISSUE TITLE
I have a deployment problem with WalletConnect-Bridge

### ISSUE THREAD

**Issue by yaoyf888** [WalletConnect/walletconnect-monorepo#537]
1. Is there an official deployment document for WalletConnect?
2. Docker has been started when I deployed, but I could not find the corresponding port for external access
3. How do I verify that the Bridge has been successfully deployed
@janus @julien51 @bpierre @miohtama @hboon

**Comment by ravisriv** [comment]
@yaoyf888

Similar issues. I'm also having problems deploying the latest WalletConnect bridge. Spent a lot of time trying to resolve. Everything works perfect but the bridge is not accessible. Generally, you can test the bridge by using the URL:   https://name-of-your-walletconnect-domain/hello

I can telnet into ports 80 and 443 but trying to connect to them from an external browser is failing continuously. The reason is too many redirects. It is possible that port 80 and 443 are playing ping-pong.
