### ISSUE TITLE
Can not connect to wallet apps in built-in browser of the Metamask

### ISSUE THREAD

**Issue by iamgamelover** [WalletConnect/walletconnect-monorepo#555]
Hi guys,

I'm trying to connect to the Metamask wallet app with Wallet Connect protocol in the built-in browser of the Metamask. :-)

First, there is showing a wallets list that I can choose a lot of wallet apps (metamask, token pocket, imtoken, etc.), and I clicked metamask's icon, then it would be directed to the App Store(I test this on iOS 14.7) and made me open/download metamask app, when I've done that and got back to metamask, it didn't connect successfully and would repeat the whole process over again and again.

For token pocket or some else in the list, click the app icon, and no response.

Pls kindly help me with the issue. Look forward to hearing from you guys!

Kevin

**Comment by foxgem** [comment]
It might be caused by the overload bridge server, you can change the version of provider to fix it. I met a similar issue these days and fixed it by changing the provider to 1.5.x.

Checking your browser console, if you find something like `Websocket connection failed`, you can try my way.

**Comment by iamgamelover** [comment]
@foxgem Thank you, Sir. I'm using the [web3-react](https://github.com/NoahZinsmeister/web3-react) library to do it. So, please check the screenshot of package.json and any issues let me know, thank you :-)

And, you said that changing the provider to 1.5.x. Which framework about the provider?

![image](https://user-images.githubusercontent.com/787620/127795146-b5e6c474-7642-4986-8486-2a19adab3c94.png)

**Comment by foxgem** [comment]
@iamgamelover I'm using `web3modal` and `@walletconnect/web3-provider`, here is the doc: https://github.com/Web3Modal/web3modal/blob/master/docs/providers/walletconnect.md . I'm not familiar with `web3-react`, but I guess it also depends on `@walletconnect/web3-provider` , you can check the doc to verify if I'm right.

**Comment by melissafzhang** [comment]
@iamgamelover were you able to resolve this?

**Comment by finessevanes** [comment]
Hey, are either of you still experiencing this issue? @melissafzhang @iamgamelover @foxgem

**Comment by melissafzhang** [comment]
@finessevanes Yes still seeing this!

**Comment by finessevanes** [comment]
@melissafzhang thanks for your reply. Would you mind filling this out to get that latest bug report on the issue? 🙏🏽

**Describe the bug**
A clear and concise description of what the bug is.

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]
 - Version [e.g. 22]


**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
