### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'generateKey' of undefined

### ISSUE THREAD

**Issue by asthap-nimblechapps** [WalletConnect/walletconnect-monorepo#75]
Hello,

I am new in this WalletConnect I am creating client sdk on browser side but getting some issue while performing createSession method. Can you please help me out with that.

Code of Walletconnect Initial Connection : 

```JAVASCRIPT
const walletConnector = new WalletConnect({
  bridge: "https://bridge.walletconnect.org" // Required
});

/**
  *  Check if connection is already established
  */
if (!walletConnector.connected) {
  // create new session
    walletConnector.createSession().then(() => {
    console.log("session");
    const uri = walletConnector.uri;
    console.log("uri" + uri);
    console.log("wallet" + walletConnector.connected);
    // display QR Code modal
    WalletConnectQRCodeModal.open(uri, () => {
      console.log("QR Code Modal closed");
    });
  });
  // walletConnector.updateSession({chainId : 0,accounts :walletConnector.accounts});
  // get uri for QR Code modal
}
/**
  *  Subscribe to connection events
  */
walletConnector.on("connect", (error, payload) => {
  console.log("connect");
  if (error) {
    throw error;
  }

  // close QR Code Modal
  WalletConnectQRCodeModal.close();

  // // get provided accounts and chainId
  // const { accounts, chainId } = payload.params[0];
});

walletConnector.on("session_update", (error, payload) => {
  console.log("session_update");
  if (error) {
    throw error;
  }

  // get updated accounts and chainId
  const { accounts, chainId } = payload.params[0];
});

walletConnector.on("disconnect", (error, payload) => {
  console.log("disconnect");
  if (error) {
    throw error;
  }

  // delete walletConnector
});
``` 

Issue while running on browser :

![screenshot 2019-02-27 at 3 57 48 pm](https://user-images.githubusercontent.com/45165629/53483851-76967780-3aa8-11e9-9239-3f68294184e2.png)

**Comment by pedrouid** [comment]
Thanks @astha-nimblechapps! 🙌 Someone else also reported this and I was about to publish beta.5 so I will just take a quick look and include the fix

**Comment by pedrouid** [comment]
I'm still confused where this error got introduced because never seen anyone reporting before beta.4

cc @rmeissner

Here is the comparison between `beta.3` and `beta.4`:

https://github.com/WalletConnect/walletconnect-monorepo/compare/1.0.0-beta.3...1.0.0-beta.4

**Comment by pedrouid** [comment]
I couldn't reproduce this issue. I've published `beta.5` for now, I will get back to this issue on `beta.6`

**Comment by astha-nimblechapps** [comment]
Thanks @pedrouid  but in browser sdk i am not getting connected in walletconnect. I send a session request by scanning code and got payload also but nothing happens at browser side. 

The following method is not working and not getting any response on @walletconnect/browser :

`
await walletConnector.on("connect", (error, payload) => {
      console.log(JSON.stringify(payload))
      if (error) {
        throw error;
      }

      // close QR Code Modal
      WalletConnectQRCodeModal.close();

      // get provided accounts and chainId
      const { accounts, chainId } = payload.params[0];
    });
`

Getting Payload response on call_request and wc_sessionRequest:

`
{"id":1551326725340790,"jsonrpc":"2.0","method":"session_request","params":[{"peerId":"66490a00-a4b8-4ad7-b1b9-c641cfdc11d7","peerMeta":{"description":"","url":"http://localhost:3001","icons":["http://localhost:3001/favicon.ico"],"name":"WalletConnect Example","ssl":false}}]}
`

**Comment by astha-nimblechapps** [comment]
> I'm still confused where this error got introduced because never seen anyone reporting before beta.4
> 
> cc @rmeissner
> 
> Here is the comparison between `beta.3` and `beta.4`:
> 
> [1.0.0-beta.3...1.0.0-beta.4](https://github.com/WalletConnect/walletconnect-monorepo/compare/1.0.0-beta.3...1.0.0-beta.4)

Can you please help me out with generate key and how to connect web to mobile using bridge server?

**Comment by koirikivi** [comment]
I got a similar issue and found this by googling, so maybe this will help someone. In my case, the issue was that I was trying to access the page with Chrome on an insecure local network url (http://192.168.1.xxx), but Chrome doesn't expose `window.crypto.subtle` in insecure contexts. Firefox seems to work, and I'd guess http://localhost... would also work.

**Comment by mkosowsk** [comment]
@koirikivi interesting! You don't happen to have those `Google` links handy, do you? 🤔

Thanks!

**Comment by koirikivi** [comment]
@mkosowsk I googled for [walletconnect Uncaught (in promise) TypeError: Cannot read property 'generateKey' of undefined](https://www.google.fi/search?q=walletconnect+Uncaught+(in+promise)+TypeError%3A+Cannot+read+property+%27generateKey%27+of+undefined) and issue this turned up on top, so that's why I decided to post here :) .

More googling led me to [this StackOverflow issue](https://stackoverflow.com/questions/46468104/how-to-use-subtlecrypto-in-chrome-window-crypto-subtle-is-undefined) and [this spec](https://www.chromium.org/blink/webcrypto), where it outlines the behaviour for insecure contexts.

**Comment by BalajiR21** [comment]
Still i'm facing this error
ERROR in node_modules/@walletconnect/core/lib/index.d.ts(24,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by pedrouid** [comment]
Hey @BalajiR21, try to update your Typescript to the latest (3.7.2) and check if this issue still persists.

**Comment by miohtama** [comment]
Just to clarify this. This error happens if you are trying to use WalletConnect on a HTTP development server. You need to serve WalletConnect over HTTPS. 

The underlying issue is that the API `window.crypto.subtle` is only enabled by web browsers when you serve over HTTPS. 

It is well laid on this MDN page: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey 

I will reopen this issue and add a helpful console.log developer message
