### ISSUE TITLE
Error: HTTPS is required for non-localhost origins

### ISSUE THREAD

**Issue by astha-nimblechapps** [WalletConnect/walletconnect-monorepo#78]
![screenshot 2019-03-04 at 3 47 36 pm](https://user-images.githubusercontent.com/45165629/53726969-26972680-3e95-11e9-8173-b640d8980d9b.png)

This issue happen when loading a wallet connect into browser with `beta 6.` 

I need help to implement Client SDK in web browser and mobile app and also create a bridge server in react(browser) and react-native(mobile app).

Is there any example of it? 

Thanks in advance. Appreciate it.

**Comment by pedrouid** [comment]
So this is related to the previous issue that you first reported about the crypto library not working on your side. I talked with @rmeissner and he debugged the problem to be related with WebCrypto where it will not work with unsecured origins excluding localhost. So it's better to throw that error and disable the library by enforcing the use of https. This also prevents MITM attacks and Port Blocking for the Websocket since it's using port 443 for HTTPS, ensuring guaranteed connection even in compromised networks
