### ISSUE TITLE
Push Notifications webhook not working for WalletConnect 1.0

### ISSUE THREAD

**Issue by jakelee8** [WalletConnect/walletconnect-monorepo#909]
Hello team!

I'm using the [Subscribe Push Notifications Webhook](https://docs.walletconnect.com/bridge-server#subscribe-push-notification-webhook) to implement push notifications.

I was able to get it working locally using the relay code in this repo and subscribing to `.walletInfo.peerId` as the push notification topic in iOS.

However, in production, the `*.bridge.walletconnect.org` servers very rarely sends a callback.

Would anyone have more info on how the Subscribe Push Notifications Webhook API works?

**Comment by jakelee8** [comment]
Not working again.

**Comment by jakelee8** [comment]
nvm, we're getting calls from WC

**Comment by matteenm** [comment]
Hi @jakelee8 , im running into this issue now. did you have to do anything to fix it?

**Comment by jakelee8** [comment]
No I did not change anything, push notifications have been working reliably since May

**Comment by matteenm** [comment]
> No I did not change anything, push notifications have been working reliably since May

and you are following the subscribe endpoint [documentation](https://docs.walletconnect.com/bridge-server#subscribe-push-notification-webhook) without any modifications? For some reason I am not getting any calls to the webhook I provide to /subscribe even though I get a success response from it.

Edit: nevermind, turns out using PeerId instead of ClientId for the topic fixed the issue.
