### ISSUE TITLE
Refactor storage dependency model, target by platform and suggest additional dependencies

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/walletconnect-monorepo#937]
Depends on: 
- https://github.com/WalletConnect/walletconnect-utils/issues/12

---

- [x] Make dependencies like `react-native-async-storage` and `better-sqlite3` externals/optionals (so that webpack doesn't bundle them)
- [x] Import and use expected external dependency (if any) for a given platform target, rather than using an injected dependency.
- [x] Update docs to reflect approach of adding additional external dependencies as needed 
- [x] Update client instantiation of `keyvaluestorage`, remove options from constructor (as we will define these on our own now)

**Comment by xzilja** [comment]
We want to take full control of storage mechanism used on all our platforms, which means that we'll no longer ask / expect users to pass their own storage library during initialisation. Similarly we will be using default database name. These require few changes:

- [ ] Remove options from constructor (as we will define these on our own now)
- [ ] Make dependencies like `react-native-async-storage` and `better-sqlite` externals (so that webpack doesn't bundle them)
- [ ] Detect which platform keyvaluestorage package is used on
- [ ] Based on platform import correct storage package
- [ ] Documentation needs to be updated to reflect these changes as users will now have to install those external packages

**Comment by bkrem** [comment]
@IljaDaderko I've merged your bullet points into the initial ones I had in the description. Only thing I've changed is instead of:


> - Detect which platform keyvaluestorage package is used on
> - Based on platform import correct storage package


we have 

> - Import and use expected external dependency for a given platform target, rather than using an injected dependency.

since `keyvaluestorage` already defines platform-specific entry targets as Pedro mentioned during sync: https://github.com/WalletConnect/walletconnect-utils/blob/master/misc/keyvaluestorage/package.json#L24

**Comment by bkrem** [comment]
Closing this since all tasks have been addressed and relevant PRs merged 👍
